ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks
    autofix_prs: true
    autoupdate_branch: main
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: quarterly
    skip: []
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.26.0'
    hooks:
      - id: eslint
        args: [--fix]
        files: \.(ts)$
        types: [file]
        language: node  
        language_version: 22.13.1
        additional_dependencies:
          - eslint@^9.26.0
          - globals@^15.15.0
          - typescript@^5.8.2
          - typescript-eslint@^8.28.0
          - neostandard@^0.12.1
          - eslint-plugin-simple-import-sort@^12.1.1
          - '@typescript-eslint/parser@^8.28.0'